version: 0.2

env:
  variables:
    ECR_URI: "565393046063.dkr.ecr.ap-south-1.amazonaws.com/aws-training"
    IMAGE_TAG: "aws-demo-ecs"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_URI:test .
      - docker tag $ECR_URI:test $ECR_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $ECR_URI:$IMAGE_TAG
      - echo Writing imageDetail file...
      - printf '{"ImageURI":"%s"}' $ECR_URI:$IMAGE_TAG > imageDetail.json
artifacts:
  files:
    - imageDetail.json
    - appspec.yaml
    - taskdef.json
